//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PelimaailmaAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pelit
    {
        public int PeliId { get; set; }
        public string Nimi { get; set; }
        public int Vuosi { get; set; }
        public string Alusta { get; set; }
        public decimal Hinta { get; set; }
    }
}
