//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PelimaailmaAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tyontekija
    {
        public int TyontekijaId { get; set; }
        public string Etunimi { get; set; }
        public string Sukunimi { get; set; }
        public string Osoite { get; set; }
        public int Puhelin { get; set; }
        public string Tehtava { get; set; }
    }
}
